export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const CARREGAMENTO = 'CARREGAMENTO';